apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
spec:
  secretName: uscrapper-tls
  duration: 2160h
  renewBefore: 360h
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  ipAddresses:
    - 35.237.56.59
